[2024-11-01T14:50:37.619+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: updating_stock_data.final_transformation scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-11-01T14:50:37.628+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: updating_stock_data.final_transformation scheduled__2024-09-30T00:00:00+00:00 [queued]>
[2024-11-01T14:50:37.629+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-11-01T14:50:37.652+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): final_transformation> on 2024-09-30 00:00:00+00:00
[2024-11-01T14:50:37.657+0000] {standard_task_runner.py:60} INFO - Started process 2740 to run task
[2024-11-01T14:50:37.660+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'updating_stock_data', 'final_transformation', 'scheduled__2024-09-30T00:00:00+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/polars_postgres.py', '--cfg-path', '/tmp/tmpuhod3ymg']
[2024-11-01T14:50:37.661+0000] {standard_task_runner.py:88} INFO - Job 206: Subtask final_transformation
[2024-11-01T14:50:37.704+0000] {task_command.py:423} INFO - Running <TaskInstance: updating_stock_data.final_transformation scheduled__2024-09-30T00:00:00+00:00 [running]> on host 07e6c451f8a5
[2024-11-01T14:50:37.772+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow_development' AIRFLOW_CTX_DAG_ID='updating_stock_data' AIRFLOW_CTX_TASK_ID='final_transformation' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T00:00:00+00:00'
[2024-11-01T14:50:37.798+0000] {python.py:202} INFO - Done. Returned value was: shape: (22, 5)
┌────────────┬─────────┬─────────┬─────────┬─────────┐
│ Date       ┆ Open    ┆ Close   ┆ Low     ┆ High    │
│ ---        ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ date       ┆ f64     ┆ f64     ┆ f64     ┆ f64     │
╞════════════╪═════════╪═════════╪═════════╪═════════╡
│ 2024-11-01 ┆ 0.65776 ┆ 0.65781 ┆ 0.65556 ┆ 0.65913 │
│ 2024-10-31 ┆ 0.65836 ┆ 0.65816 ┆ 0.65729 ┆ 0.65859 │
│ 2024-10-30 ┆ 0.65728 ┆ 0.65728 ┆ 0.65405 ┆ 0.658   │
│ 2024-10-29 ┆ 0.6563  ┆ 0.6563  ┆ 0.65374 ┆ 0.65954 │
│ 2024-10-28 ┆ 0.65827 ┆ 0.65827 ┆ 0.65459 ┆ 0.6586  │
│ …          ┆ …       ┆ …       ┆ …       ┆ …       │
│ 2024-10-09 ┆ 0.67174 ┆ 0.67174 ┆ 0.67136 ┆ 0.67417 │
│ 2024-10-08 ┆ 0.67396 ┆ 0.67396 ┆ 0.67083 ┆ 0.67606 │
│ 2024-10-07 ┆ 0.6756  ┆ 0.6756  ┆ 0.67183 ┆ 0.677   │
│ 2024-10-06 ┆ 0.68006 ┆ 0.68006 ┆ 0.67589 ┆ 0.6812  │
│ 2024-10-03 ┆ 0.68503 ┆ 0.68503 ┆ 0.67884 ┆ 0.6852  │
└────────────┴─────────┴─────────┴─────────┴─────────┘
[2024-11-01T14:50:37.810+0000] {xcom.py:664} ERROR - Object of type bytes is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2024-11-01T14:50:37.812+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'bytes'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 451, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3013, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2024-11-01T14:50:37.818+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=updating_stock_data, task_id=final_transformation, execution_date=20240930T000000, start_date=20241101T145037, end_date=20241101T145037
[2024-11-01T14:50:37.828+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 206 for task final_transformation (Object of type bytes is not JSON serializable; 2740)
[2024-11-01T14:50:37.873+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-01T14:50:37.897+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
